Limitless_CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('task_manager.urls')),
    path('', include('crm.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/urls.py
# crm/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/add/', views.add_customer, name='add_customer'),
    path('customers/edit/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('customers/delete/<int:customer_id>/', views.delete_customer, name='delete_customer'),
    path('upload_document/', views.upload_document, name='upload_document'),
    path('document_list/', views.document_list, name='document_list'),
    path('delete_document/<int:document_id>/', views.delete_document, name='delete_document'),
]

task_manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('create/', views.create_or_edit_task, name='create_task'),
    path('edit/<int:task_id>/', views.create_or_edit_task, name='edit_task'),
    path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
]

task_manager/models.py
from django.db import models
from django.contrib.auth.models import User
STATUS_CHOICES = (
    ('not_started', 'Not started'),
    ('in_progress', 'In progress'),
    ('completed', 'Completed'),
)
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=200)
    description = models.TextField()
    assigned_to_name = models.CharField(max_length=100, blank=True, null=True)
    assigned_to_position = models.CharField(max_length=100, blank=True, null=True)
    assigned_to_email = models.EmailField(blank=True, null=True)
    due_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='not_started')

    def __str__(self):
        return self.title

task_manager/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'assigned_to_name', 'assigned_to_position', 'assigned_to_email',
                  'due_date', 'status']

task_manager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import TaskForm
from django.utils import timezone
from django.db.models import F, Case, When, Value


def task_list(request):
    user = request.user

    tasks = Task.objects.filter(
        user=user
    ).order_by(
        Case(
            When(due_date__isnull=True, then=Value(timezone.datetime.max)),
            default=F('due_date'),
        )
    )

    for task in tasks:
        due_date = task.due_date
        if due_date:
            time_diff = (due_date - timezone.now()).days
            if time_diff < 7:
                task.priority = 'High Priority'
            elif 7 <= time_diff < 14:
                task.priority = 'Medium Priority'
            else:
                task.priority = 'Low Priority'
        else:
            task.priority = 'No Due Date'

    return render(request, 'task_manager/task_list.html', {'tasks': tasks})


def create_or_edit_task(request, task_id=None):
    if task_id:
        task = get_object_or_404(Task, id=task_id)
    else:
        task = None
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            task = form.save(commit=False)  
            task.user = request.user 
            task.save()
            return redirect('task_list')

    else:
        if task and  task.due_date:
            initial_data = {'due_date': task.due_date.strftime('%Y-%m-%dT%H:%M') if task else None}
            form = TaskForm(instance=task, initial=initial_data)
        else:

            form = TaskForm(instance=task)

    return render(request, 'task_manager/task_form.html', {'form': form})


def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    task.delete()
    return redirect('task_list')

task_manager/templates/task_manager/task_form.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5">
    <h2>Task Form</h2>
    <form method="post" id="taskForm">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group  mb-4">
                <label for="id_title">Task Title:</label>
                <input type="text" class="form-control {% if form.title.errors %}is-invalid{% endif %}" id="id_title" name="title" value="{{ form.title.value|default_if_none:"" }}">
                {% if form.title.errors %}
                    <div class="invalid-feedback">
                        {{ form.title.errors|join:", " }}
                    </div>
                {% endif %}
            </div>

        </div>
        <div class="form-row">
            <div class="form-group  mb-4">
                <label for="id_assigned_to_name">Assigned To:</label>
                <input type="text" class="form-control {% if form.assigned_to_name.errors %}is-invalid{% endif %}" id="id_assigned_to_name" name="assigned_to_name" value="{{ form.assigned_to_name.value|default_if_none:"" }}">
                {% if form.assigned_to_name.errors %}
                    <div class="invalid-feedback">
                        {{ form.assigned_to_name.errors|join:", " }}
                    </div>
                {% endif %}
            </div>
            <div class="form-group  mb-4">
                <label for="id_assigned_to_position">Position:</label>
                <input type="text" class="form-control {% if form.assigned_to_position.errors %}is-invalid{% endif %}" id="id_assigned_to_position" name="assigned_to_position" value="{{ form.assigned_to_position.value|default_if_none:"" }}">
                {% if form.assigned_to_position.errors %}
                    <div class="invalid-feedback">
                        {{ form.assigned_to_position.errors|join:", " }}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group mb-4">
            <label for="id_assigned_to_email">Email Address:</label>
            <input type="email" class="form-control {% if form.assigned_to_email.errors %}is-invalid{% endif %}" id="id_assigned_to_email" name="assigned_to_email" value="{{ form.assigned_to_email.value|default_if_none:"" }}">
            {% if form.assigned_to_email.errors %}
                <div class="invalid-feedback">
                    {{ form.assigned_to_email.errors|join:", " }}
                </div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="id_description">Description:</label>
            <textarea class="form-control {% if form.description.errors %}is-invalid{% endif %}" id="id_description" name="description">{{ form.description.value|default_if_none:"" }}</textarea>
            {% if form.description.errors %}
                <div class="invalid-feedback">
                    {{ form.description.errors|join:", " }}
                </div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="id_due_date">Due Date:</label>
            <input type="datetime-local" class="form-control {% if form.due_date.errors %}is-invalid{% endif %}" id="id_due_date" name="due_date" value="{{ form.due_date.value|default_if_none:'' }}">
            {% if form.due_date.errors %}
                <div class="invalid-feedback">
                    {{ form.due_date.errors|join:", " }}
                </div>
            {% endif %}
        </div>
        <div class="form-group mb-4">
            <label for="id_status">Status:</label>
            <select class="form-control {% if form.status.errors %}is-invalid{% endif %}" id="id_status" name="status">
                <option value="not_started">Not Started</option>
                <option value="in_progress">In progress</option>
                <option value="completed">Completed</option>
            </select>
            {% if form.status.errors %}
                <div class="invalid-feedback">
                    {{ form.status.errors|join:", " }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'task_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>

<!-- Bootstrap Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


{% endblock %}

task_manager/templates/task_manager/task_list.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Limitless CRM -Tasks{% endblock %}
{% block content %}

<div class="container mt-5 text-center">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <div class="row">

            <h2 class="text-dark mb-0">Tasks</h2>
        </div>
        <div class="row d-flex align-items-start">

             <div class="form-group  mr-3 w-50">
                <input type="text" class="form-control border-success" id="searchInput" placeholder="Search Task">
            </div>
            <a href="{% url 'create_task' %}" class="btn btn-outline-success w-50">+ New Task</a>
        </div>


    </div>

    <!-- Task List Table -->
    <div class="table-responsive">
        <table class="table " id="taskTable">
            <thead class="table-dark">
            <tr>
                <th scope="col" class="clickable" data-column="1">Title <span class="arrow"></span></th>
                <th scope="col" class="clickable" data-column="2">Priority <span class="arrow"></span></th>
                <th scope="col">Assigned To</th>
                <th scope="col" class="clickable" data-column="4">Due Date <span class="arrow"></span></th>
                <th scope="col" class="clickable" data-column="5">Status <span class="arrow"></span></th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for task in tasks %}
            <tr class="clickable-row" data-href="{% url 'edit_task' task.id %}">
                <td>{{ task.title }}</td>
                <td data-value="{{ task.priority }}">{{ task.priority }}</td>
                <td>
                    {% if task.assigned_to_name %}
                        {{ task.assigned_to_name }}
                    {% endif %}
                </td>
                <td data-value="{{ task.due_date }}">
                    {% if task.due_date %}
                        {{ task.due_date|date:"d/m/Y H:i" }}
                    {% endif %}
                </td>
                <td data-value="{{ task.status }}">
                    {% if task.status %}
                        {{ task.get_status_display }}
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'edit_task' task.id %}" class="btn btn-primary btn-sm">Detail</a>
                    <button  type="button" class="btn btn-danger btn-sm btn-delete-task btn-canel-task" data-id="{{ task.id }}">Delete</button>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No tasks found.</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Confirm Delete Modal -->
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Delete</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this task?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="#" class="btn btn-danger btn-confirm-delete">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>



{% endblock %}

{% block js %}
<script src="{% static 'js/task_list.js' %}"></script>
<script>
    const deleteUrls = "{% url 'delete_task' 0 %}";
</script>

{% endblock %}